package com.daklok.biblelockscreen.strings

// deStrings -- auto-extracted from MainActivity.kt (original lines 1444..1663).
val deStrings = AppStrings().apply {
    updateTime = "Zeitliche Aktualisierungszeit"
    settings = "App-Einstellungen"
    dailyWallpaper = "Tägliches Hintergrundbild"
    active = "Aktiv (jeden Tag bei %s:00)"
    inactive = "Inaktiv"
    textCustomization = "Textanpassung"
    bold = "Fett"
    shadow = "Schatten"
    textSize = "Textgröße"
    textWidth = "Textbreite"
    textHeight = "Texthöhe"
    textAlpha = "Transparenz"
    bgBlur = "Hintergrundunschärfe"
    bgDarknessLabel = "Hintergrund abdunkeln"
    anotherPhoto = "Anderes Foto"
    test = "Erzeugen"
    selectPhotoFirst = "Wähle zuerst ein Foto aus"
    appearance = "Erscheinungsbild"
    system = "System"
    light = "Hell"
    dark = "Dunkel"
    dynamicColor = "Material You (Systemfarben)"
    haptics = "Haptisches Feedback"
    hapticsDesc = "Vibrationen beim Bearbeiten"
    support = "Unterstützung"
    supportDesc = "Wenn dir die App gefällt und du ihre Entwicklung unterstützen möchtest, kannst du mir einen Kaffee spendieren ☕"
    donate = "Spenden"
    close = "Schließen"

    dragHint = "Ziehe die Punkte für die Größe und Breite\nZiehe in die Mitte zum Bewegen"
    cancel = "Abbrechen"
    done = "Fertig"
    clickToSelect = "Tippe, um ein Foto auszuwählen"
    loading = "Lade Vers..."
    appLanguage = "App-Sprache"
    verseLanguage = "Vers-Sprache"
    language = "Sprache"
    dailyWorkerOn = "Aktiviert!\nHintergrundbild ändert sich morgen um %s:00."
    dailyWorkerOff = "Tägliche Änderung deaktiviert."
    generating = "Hintergrundbild wird generiert..."
    fontModern = "Modern"

    fontBook = "Buch"
    fontMono = "Schreibmaschine"
    fontCursive = "Kursiv"
    fontLight = "Leicht"
    fontCondensed = "Schmal"

    generatingBtn = "Generieren..."
    tapToEdit = "Tippe, um die Position und Größe zu ändern"
    batteryWarningTitle = "Akku-Warnung"
    batteryWarningDesc = "Damit der automatische Hintergrundwechsel zuverlässig funktioniert, deaktivieren Sie bitte die Akku-Optimierung für diese App."
    batteryWarningButton = "Optimierung Deaktivieren"
    customVerseTitle = "Eigener Text"
    customVerseHint = "Verstext..."
    customRefHint = "Koordinaten (z.B. Johannes 3:16)"
    applyCustom = "Anwenden"
    autoWallpaper = "Automatischer Hintergrundwechsel"
    autoWallpaperIntervalLabel = "Wechselintervall"
    autoWallpaperEvery1h = "Jede Stunde"
    autoWallpaperEvery2h = "Alle 2 Stunden"
    autoWallpaperEvery3h = "Alle 3 Stunden"
    autoWallpaperEvery6h = "Alle 6 Stunden"
    autoWallpaperEvery12h = "Alle 12 Stunden"
    autoWallpaperEvery24h = "Alle 24 Stunden (täglich)"
    autoWallpaperOnScreenOff = "Beim Ausschalten des Bildschirms"
    autoWallpaperOnScreenOffDesc = "Der Vers ändert sich bei jeder Sperrung"
    autoWallpaperTimeLabel = "Uhrzeit des täglichen Wechsels"
    autoWallpaperActiveHourly = "Aktiv (alle %sh)"
    autoWallpaperActiveDaily = "Aktiv (täglich um %s:00)"
    autoWallpaperActiveScreenOff = "Aktiv (bei Sperrung)"
    autoWorkerOn = "Aktiviert! Das Hintergrundbild wechselt nach dem eingestellten Intervall."
    autoWorkerOff = "Automatischer Wechsel deaktiviert."
    colorPickerTitle = "Farbe auswählen"
    colorPickerBrightness = "Helligkeit"
    colorPickerVerseColor = "Versfarbe"

    // Wallpaper target
    wallpaperTargetLabel = "Hintergrundbild anwenden auf"
    wallpaperTargetLock = "Sperrbildschirm"
    wallpaperTargetHome = "Startbildschirm"
    wallpaperTargetBoth = "Beide"

    // Verse database section
    vdbTitle = "Vers-Datenbanken"
    vdbSubtitle = "Erstelle, importiere oder exportiere Sammlungen"
    vdbManage = "Verwalten"
    vdbNewDatabase = "Neue Datenbank"
    vdbEditPrefix = "Bearbeiten ·"
    vdbImportExport = "Importieren / Exportieren"
    vdbCreateNew = "Neu erstellen"
    vdbSectionCustom = "Benutzerdefiniert"
    vdbSectionBuiltIn = "Integriert"
    vdbHint = "Tippe auf \u201eVerwenden\u201c bei einer benutzerdefinierten Datenbank, um sie als aktive Versquelle festzulegen — oder wähle sie später unter Einstellungen → Verssprache."
    vdbUse = "Verwenden"
    vdbUsed = "Aktiviert"
    vdbDeleteTitle = "Löschen"
    vdbDeleteText = "Verse werden dauerhaft entfernt."
    vdbDelete = "Löschen"
    vdbDeleted = "Gelöscht"
    vdbVerses = "Verse"
    vdbCustomLabel = "Benutzerdefiniert"
    vdbCodeLabel = "Code"
    vdbCodePlaceholder = "z.B. LUT"
    vdbCodeHint = "Wähle diesen unter Einstellungen → Verssprache"
    vdbUpdate = "Aktualisieren"
    vdbSave = "Speichern"
    vdbNoVerses = "Keine Verse — tippe unten auf +"
    vdbVersesFilled = "ausgefüllt"
    vdbVerse = "Vers"
    vdbVersePlural = "Verse"
    vdbClearAll = "Alle löschen"
    vdbNoVersesYet = "Noch keine Verse"
    vdbAddFirstVerse = "Tippe auf die Schaltfläche unten, um deinen ersten Vers hinzuzufügen"
    vdbAddVerse = "Vers hinzufügen"
    vdbVerseText = "Verstext"
    vdbReference = "Referenz"
    vdbReferencePlaceholder = "z.B. Johannes 3:16"
    vdbVerseCard = "Vers"
    vdbUpdated = "Aktualisiert"
    vdbCreated = "Erstellt"
    vdbErrorCode = "Gib einen Datenbankcode ein"
    vdbErrorVerse = "Füge mindestens einen Vers hinzu"
    vdbErrorFailed = "Fehler"
    vdbImportTitle = "Importieren"
    vdbImportJson = "JSON-Datei importieren"
    vdbImportDesc = "Wähle eine Vers-JSON-Datei vom Gerät"
    vdbBrowse = "Durchsuchen"
    vdbImporting = "Importiere..."
    vdbImportCodeTitle = "Datenbankcode"
    vdbImportCodeDesc = "Gib einen kurzen Code für diese Datenbank ein (z.B. LUT). Sie überschreibt die integrierte Datenbank, wenn der Code übereinstimmt."
    vdbImport = "Importieren"
    vdbImportSuccess = "%d Verse importiert als"
    vdbImportFailed = "Import fehlgeschlagen"
    vdbExportCustom = "Exportieren — Benutzerdefiniert"
    vdbExportBuiltIn = "Exportieren — Integriert"
    vdbExport = "Exportieren"
    vdbExporting = "Wird in Downloads gespeichert…"
    vdbExportDone = "In Downloads gespeichert"
    vdbExportFailed = "Export fehlgeschlagen"
    vdbJsonFormat = "JSON-Format"

    // Backup & Restore
    backupTitle = "Sicherung & Wiederherstellung"
    backupExport = "Einstellungen sichern"
    backupExportDesc = "Speichert alle Einstellungen, das Hintergrundbild und die Datenbanken in einer Datei"
    backupImport = "Aus Sicherung wiederherstellen"
    backupImportDesc = "Ersetzt alle aktuellen Einstellungen, das Hintergrundbild und die Datenbanken"
    backupExporting = "Sichere…"
    backupImporting = "Stelle wieder her…"
    backupExportSuccess = "Sicherung gespeichert · %d Einstellungen, %d Datenbanken"
    backupImportSuccess = "Sicherung wiederhergestellt · %d Einstellungen, %d Datenbanken. Neustart…"
    backupExportFailed = "Sicherung fehlgeschlagen"
    backupImportFailed = "Wiederherstellung fehlgeschlagen"
    backupConfirmTitle = "Aus Sicherung wiederherstellen?"
    backupConfirmDesc = "Dies ersetzt alle deine aktuellen Einstellungen, das Hintergrundbild und die Datenbanken. Vorgang nicht umkehrbar."

    // Wallpaper gallery screen
    wpScreenTitle = "Hintergrundbilder"
    wpScreenSubtitle = "Verwalte deine Hintergrundbilder und automatische Rotation"
    wpGalleryEmpty = "Keine Hintergrundbilder"
    wpGalleryEmptyDesc = "Füge dein erstes Hintergrundbild hinzu — wähle ein Foto aus der Galerie."
    wpAdd = "Hintergrundbild hinzufügen"
    wpSetActive = "Verwenden"
    wpActive = "Aktiv"
    wpDelete = "Entfernen"
    wpDeleteConfirm = "Dieses Hintergrundbild entfernen?"
    wpDeleteConfirmDesc = "Das Hintergrundbild wird dauerhaft aus der App entfernt."
    wpCycleTitle = "Automatische Rotation"
    wpCycleDesc = "Wechselt Hintergrundbilder automatisch nach einem Intervall"
    wpCycleInterval = "Rotationsintervall"
    wpCycleDailyHour = "Tägliche Wechselzeit"
    wpCycleOnScreenOff = "Beim Sperren"
    wpCycleOnScreenOffDesc = "Wechselt das Hintergrundbild bei jedem Sperren des Telefons"
    wpNightMode = "Nachtmodus"
    wpNightModeDesc = "Nachts ein anderes Hintergrundbild verwenden"
    wpNightStart = "Nacht beginnt"
    wpNightEnd = "Nacht endet"
    wpActiveBadge = "Aktiv"
    wpNightBadge = "Nacht"
    wpCycleModeVerse = "Bei Verswechsel"
    wpCycleModeInterval = "Eigenes Intervall"
    wpCycleModeScreenOff = "Bei jedem Sperren"
    wpCycleModeDayNight = "Tag / Nacht"
    wpCycleModeVerseDesc = "Hintergrundbild wechselt mit dem Vers"
    wpCycleModeDayNightDesc = "Automatisch zwischen Tag- und Nachthintergrund wechseln"
    wpCycleDayWallpaper = "Tag-Hintergrund"
    wpCycleNightWallpaper = "Nacht-Hintergrund"
    wpCycleModeIntervalDesc = "Wechsel in festen Intervallen"
    wpCycleModeScreenOffDesc = "Wechsel bei jedem Sperren"
    wpDualLockWarning = "Der Hintergrundwechsel bei ausgeschaltetem Bildschirm kann bis zu 3 Sekunden dauern."
    wpDayStart = "Tag beginnt"
    wpDayEnd = "Tag endet"

    wpViewAll = "Alle ansehen"
    wpViewAllTitle = "Alle Hintergrundbilder"
    wpSelectMode = "Auswählen"
    wpDeleteSelected = "Ausgewählte löschen"
    wpSelected = "ausgewählt"
    wpDeleteAllConfirm = "Ausgewählte Hintergrundbilder löschen?"
    wpDeleteAllConfirmDesc = "Die ausgewählten Hintergrundbilder werden dauerhaft aus der App entfernt."
    wpPageHint = "Wische nach links für Hintergrundbilder →"

    // Verse language source toggle (in Settings)
    vdbSourceDefault = "Standard"
    vdbSourceCustom = "Eigene"
    vdbSourceFavorites = "Favoriten"
    vdbFavoritesCycling = "Wechsel zwischen %d Favoriten-Versen"
    vdbFavoritesEmptyCta = "Füge zuerst Favoriten hinzu"
    vdbEmptyCustom = "Noch keine eigenen Datenbanken"
    vdbEmptyCustomDesc = "Erstelle deine eigene Verssammlung, z. B. KJV oder eine andere Übersetzung."
    vdbEmptyCustomCta = "Neue Datenbank erstellen"

    // Duplicate-code warnings + import conflict dialog
    vdbWarningCodeBuiltin = "Code \"%s\" wird bereits von einer integrierten Datenbank verwendet. Du kannst ihn trotzdem verwenden — die eigene DB teilt sich den Code."
    vdbWarningCodeCustom = "Code \"%s\" existiert bereits als eigene Datenbank. Speichern überschreibt sie."
    vdbImportConflictTitle = "Code existiert bereits"
    vdbImportConflictDesc = "Eine eigene Datenbank mit Code \"%s\" existiert bereits. Gib einen anderen Code ein, oder behalte \"%s\" zum Überschreiben."
    vdbImportConflictAction = "Mit diesem Code importieren"

    // Overwrite confirmation dialog (CreateEditScreen — Save with existing custom code)
    vdbOverwriteTitle = "Datenbank überschreiben?"
    vdbOverwriteDesc = "Eine eigene Datenbank mit Code \"%s\" existiert bereits. Speichern überschreibt ihre Verse dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden."
    vdbOverwriteConfirm = "Überschreiben"
    share = "Teilen"
    shareDialogTitle = "Vers teilen"
    shareDialogDesc = "Aktion wählen"
    shareAction = "Teilen"
    shareActionDesc = "Bild über andere Apps senden"
    saveToGalleryAction = "In Galerie speichern"
    saveToGalleryActionDesc = "Bild auf dem Gerät speichern"
    shareSuccess = "Vers geteilt"
    shareFailed = "Teilen fehlgeschlagen"
    saveSuccess = "Vers in Galerie gespeichert"
    saveFailed = "Speichern fehlgeschlagen"
    shareImageDesc = "Bild mit Vers zum Teilen"

    // --- Favorite verses ---
    favorites = "Favoriten"
    favoritesTitle = "Lieblingsverse"
    favoritesEmpty = "Du hast noch keine Lieblingsverse"
    favoritesEmptyDesc = "Füge einen Vers hinzu, indem du auf den Stern in der Vorschau tippst."
    addToFavorites = "Zu Favoriten hinzufügen"
    removeFromFavorites = "Aus Favoriten entfernen"
    favoritesCount = "%d Favoriten"
    setAsWallpaper = "Als Hintergrundbild festlegen"
    confirmRemoveFavoriteTitle = "Aus Favoriten entfernen?"
    confirmRemoveFavoriteDesc = "Dieser Vers wird aus deinen Favoriten entfernt."
    addedToFavorites = "Vers zu Favoriten hinzugefügt"
    removedFromFavorites = "Vers aus Favoriten entfernt"
    addedOn = "Hinzugefügt am %s"
    favoritesSubtitle = "Tippe auf einen Vers, um ihn als Hintergrund festzulegen"
    favCardStyleLabel = "Favoriten-Kartenstil"
    favCardStyleQuote = "Detailliert"
    favCardStyleCompact = "Kompakt"
    favCardStyleHero = "Zitat"
    favCardStyleQuoteDesc = "Vers mit Aktionsleiste"
    favCardStyleCompactDesc = "Kompakte Zeile"
    favCardStyleHeroDesc = "Großes Zitat wie ein Poster"

}

// Localized language names in German (top-level, see AppStrings.kt for why).
val deLocalizedLangNames: Map<String, String> = mapOf(
    "EN" to "Englisch",
    "SK" to "Slowakisch",
    "CZ" to "Tschechisch",
    "ES" to "Spanisch",
    "IT" to "Italienisch",
    "FR" to "Französisch",
    "DE" to "Deutsch",
    "HU" to "Ungarisch",
    "PL" to "Polnisch"
)
