package com.daklok.biblelockscreen.strings

// skStrings -- Slovak translations (source language).
val skStrings = AppStrings(
    test = "Generovať",
    generatingBtn = "Generuje sa...",
    generating = "Tapeta sa generuje...",
    done = "Hotovo",

    updateTime = "Čas dennej aktualizácie",

    tapToEdit = "Kliknutím upravíš polohu a veľkosť",
    settings = "Nastavenia aplikácie",
    dailyWallpaper = "Denná zmena tapety",
    active = "Aktívne (každý deň o %s:00)",
    inactive = "Vypnuté",

    textCustomization = "Prispôsobenie textu",
    bold = "Tučné",
    shadow = "Tieň",
    textSize = "Veľkosť písma",
    textWidth = "Šírka textu",
    textHeight = "Výška textu",
    textAlpha = "Priehľadnosť",
    bgBlur = "Rozmazanie pozadia",
    bgDarknessLabel = "Stmavenie pozadia",
    anotherPhoto = "Iná fotka",
    selectPhotoFirst = "Najskôr vyber fotku",
    appearance = "Vzhľad",
    system = "Systém",
    light = "Svetlý",
    dark = "Tmavý",
    dynamicColor = "Material You (Farby systému)",
    haptics = "Haptická odozva",
    hapticsDesc = "Vibrácie pri upravovaní widgetu",
    support = "Podpora",
    supportDesc = "Ak sa ti aplikácia páči a chceš podporiť jej vývoj, môžeš mi kúpiť kávu ☕",
    donate = "Prispieť",
    close = "Zavrieť",
    dragHint = "Ťahaj body pre veľkosť a šírku\nŤahaj do stredu pre presun",

    cancel = "Zrušiť",
    clickToSelect = "Klikni pre výber fotky",
    loading = "Načítavam verš...",
    appLanguage = "Jazyk aplikácie",
    verseLanguage = "Jazyk veršov",
    language = "Jazyk",
    dailyWorkerOn = "Zapnuté!\nTapeta sa zmení zajtra o %s:00.",
    dailyWorkerOff = "Denná zmena bola vypnutá.",
    fontModern = "Moderný",
    fontBook = "Knižný",

    fontMono = "Strojový",
    fontCursive = "Písaný",
    fontLight = "Tenký",
    fontCondensed = "Úzky",

    // Battery strings
    batteryWarningTitle = "Upozornenie na batériu",
    batteryWarningDesc = "Pre správne fungovanie automatickej zmeny tapety na pozadí, prosím, vypnite optimalizáciu batérie pre túto aplikáciu.",
    batteryWarningButton = "Vypnúť optimalizáciu",

    // Custom Verse strings
    customVerseTitle = "Vlastný text",
    customVerseHint = "Text verša...",
    customRefHint = "Súradnice (napr. Ján 3:16)",
    applyCustom = "Použiť",

    // Automatic Wallpaper Change strings
    autoWallpaper = "Automatická zmena tapety",
    autoWallpaperIntervalLabel = "Interval zmeny",
    autoWallpaperEvery1h = "Každú hodinu",
    autoWallpaperEvery2h = "Každé 2 hodiny",
    autoWallpaperEvery3h = "Každé 3 hodiny",
    autoWallpaperEvery6h = "Každých 6 hodín",
    autoWallpaperEvery12h = "Každých 12 hodín",
    autoWallpaperEvery24h = "Každých 24 hodín (denne)",
    autoWallpaperOnScreenOff = "Pri vypnutí obrazovky",
    autoWallpaperOnScreenOffDesc = "Verš sa zmení pri každom zamknutí telefónu",
    autoWallpaperTimeLabel = "Čas dennej zmeny",
    autoWallpaperActiveHourly = "Aktívne (každých %sh)",
    autoWallpaperActiveDaily = "Aktívne (denne o %s:00)",
    autoWallpaperActiveScreenOff = "Aktívne (pri zamknutí)",
    autoWorkerOn = "Zapnuté! Tapeta sa zmení podľa nastaveného intervalu.",
    autoWorkerOff = "Automatická zmena bola vypnutá.",

    // Color picker
    colorPickerTitle = "Vybrať farbu",
    colorPickerBrightness = "Jas",
    colorPickerVerseColor = "Farba verša",

    // Wallpaper target
    wallpaperTargetLabel = "Použiť tapetu na",
    wallpaperTargetLock = "Zamknutá",
    wallpaperTargetHome = "Domov",
    wallpaperTargetBoth = "Oboje",

    // Verse database section
    vdbTitle = "Databázy veršov",
    vdbSubtitle = "Vytvor, importuj alebo exportuj zbierky",
    vdbManage = "Spravovať",
    vdbNewDatabase = "Nová databáza",
    vdbEditPrefix = "Upraviť ·",
    vdbImportExport = "Import / Export",
    vdbCreateNew = "Vytvoriť novú",
    vdbSectionCustom = "Vlastné",
    vdbSectionBuiltIn = "Vstavaná",
    vdbHint = "Vlastnú DB vyberieš cez Nastavenia → Jazyk veršov",
    vdbDeleteTitle = "Zmazať",
    vdbDeleteText = "verzov bude natrvalo odstránených.",
    vdbDelete = "Zmazať",
    vdbDeleted = "Zmazané",
    vdbVerses = "veršov",
    vdbCustomLabel = "Vlastné",
    vdbCodeLabel = "Kód",
    vdbCodePlaceholder = "napr. KJV",
    vdbCodeHint = "Vyber v Nastavenia → Jazyk veršov",
    vdbUpdate = "Aktualizovať",
    vdbSave = "Uložiť",
    vdbNoVerses = "Žiadne verše — klepni na + nižšie",
    vdbVersesFilled = "vyplnených",
    vdbVerse = "verš",
    vdbVersePlural = "veršov",
    vdbClearAll = "Vymazať všetko",
    vdbNoVersesYet = "Zatiaľ žiadne verše",
    vdbAddFirstVerse = "Klepni na tlačidlo nižšie a pridaj prvý verš",
    vdbAddVerse = "Pridať verš",
    vdbVerseText = "Text verša",
    vdbReference = "Súradnice",
    vdbReferencePlaceholder = "napr. Ján 3:16",
    vdbVerseCard = "Verš",
    vdbUpdated = "Aktualizovaná",
    vdbCreated = "Vytvorená",
    vdbErrorCode = "Zadaj kód databázy",
    vdbErrorVerse = "Pridaj aspoň jeden verš",
    vdbErrorFailed = "Chyba",
    vdbImportTitle = "Import",
    vdbImportJson = "Importovať JSON súbor",
    vdbImportDesc = "Vyber verse .json zo zariadenia",
    vdbBrowse = "Prehľadávať",
    vdbImporting = "Importujem...",
    vdbImportCodeTitle = "Kód databázy",
    vdbImportCodeDesc = "Zadaj krátky kód pre túto databázu (napr. KJV). Prepíše vstavanú databázu ak sa kód zhoduje.",
    vdbImport = "Importovať",
    vdbImportSuccess = "Importovaných %d veršov ako",
    vdbImportFailed = "Import zlyhal",
    vdbExportCustom = "Export — Vlastné",
    vdbExportBuiltIn = "Export — Vstavaná",
    vdbExport = "Exportovať",
    vdbExporting = "Ukladám do Downloads…",
    vdbExportDone = "Uložené do Downloads",
    vdbExportFailed = "Export zlyhal",
    vdbJsonFormat = "Formát JSON",

    // Backup & Restore
    backupTitle = "Záloha a obnova",
    backupExport = "Zálohovať nastavenia",
    backupExportDesc = "Uloží všetky nastavenia, tapetu a databázy do jedného súboru",
    backupImport = "Obnoviť zo zálohy",
    backupImportDesc = "Nahradí všetky aktuálne nastavenia, tapetu a databázy",
    backupExporting = "Zálohujem…",
    backupImporting = "Obnovujem…",
    backupExportSuccess = "Záloha uložená · %d nastavení, %d databáz",
    backupImportSuccess = "Záloha obnovená · %d nastavení, %d databáz. Reštartujem…",
    backupExportFailed = "Záloha zlyhala",
    backupImportFailed = "Obnova zlyhala",
    backupConfirmTitle = "Obnoviť zo zálohy?",
    backupConfirmDesc = "Toto nahradí všetky tvoje aktuálne nastavenia, tapetu a databázy. Akciu nie je možné vrátiť späť.",

    // Wallpaper gallery screen
    wpScreenTitle = "Tapety",
    wpScreenSubtitle = "Spravuj svoje tapety a automatické striedanie",
    wpGalleryEmpty = "Žiadne tapety",
    wpGalleryEmptyDesc = "Pridaj svoju prvú tapetu — vyber fotku z galérie.",
    wpAdd = "Pridať tapetu",
    wpSetActive = "Použiť",
    wpActive = "Aktívna",
    wpDelete = "Odstrániť",
    wpDeleteConfirm = "Odstrániť túto tapetu?",
    wpDeleteConfirmDesc = "Tapeta bude natrvalo odstránená z aplikácie.",
    wpCycleTitle = "Automatické striedanie",
    wpCycleDesc = "Striedaj tapety automaticky podľa intervalu",
    wpCycleInterval = "Interval striedania",
    wpCycleDailyHour = "Čas dennej zmeny",
    wpCycleOnScreenOff = "Pri zamknutí",
    wpCycleOnScreenOffDesc = "Zmení tapetu pri každom zamknutí telefónu",
    wpNightMode = "Nočný režim",
    wpNightModeDesc = "Použiť inú tapetu v noci",
    wpNightStart = "Začiatok noci",
    wpNightEnd = "Koniec noci",
    wpActiveBadge = "Aktívna",
    wpNightBadge = "Nočná",
    wpCycleModeVerse = "Pri zmene verša",
    wpCycleModeInterval = "Vlastný interval",
    wpCycleModeScreenOff = "Pri zamknutí",
    wpCycleModeDayNight = "Deň / Noc",
    wpCycleModeVerseDesc = "Tapeta sa zmení spolu s veršom",
    wpCycleModeDayNightDesc = "Automaticky prepínať medzi dennou a nočnou tapetou",
    wpCycleDayWallpaper = "Denná tapeta",
    wpCycleNightWallpaper = "Nočná tapeta",
    wpCycleModeIntervalDesc = "Zmena v pevných intervaloch",
    wpCycleModeScreenOffDesc = "Zmena pri každom zamknutí",
    wpDualLockWarning = "Zmena tapety pri vypnutom displeji môže trvať až 3 sekundy.",
    wpDayStart = "Začiatok dňa",
    wpDayEnd = "Koniec dňa",

    wpViewAll = "Zobraziť všetky",
    wpViewAllTitle = "Všetky tapety",
    wpSelectMode = "Vybrať",
    wpDeleteSelected = "Odstrániť vybrané",
    wpSelected = "vybraných",
    wpDeleteAllConfirm = "Odstrániť vybrané tapety?",
    wpDeleteAllConfirmDesc = "Vybrané tapety budú natrvalo odstránené z aplikácie.",
    wpPageHint = "Potiahni doľava pre tapety →",

    // Verse language source toggle (in Settings)
    vdbSourceDefault = "Vstavané",
    vdbSourceCustom = "Vlastné",
    vdbEmptyCustom = "Zatiaľ žiadne vlastné databázy",
    vdbEmptyCustomDesc = "Vytvor si vlastnú zbierku veršov — napríklad pre KJV alebo iný preklad.",
    vdbEmptyCustomCta = "Vytvoriť novú databázu",

    // Duplicate-code warnings + import conflict dialog
    vdbWarningCodeBuiltin = "Kód \"%s\" je už použitý vstavanou databázou. Môžeš ho použiť — vlastná DB bude zdieľať kód.",
    vdbWarningCodeCustom = "Kód \"%s\" už existuje ako vlastná databáza. Uloženie ju prepíše.",
    vdbImportConflictTitle = "Kód už existuje",
    vdbImportConflictDesc = "Vlastná databáza s kódom \"%s\" už existuje. Zadaj iný kód, alebo nech \"%s\" na prepísanie.",
    vdbImportConflictAction = "Importovať s týmto kódom",

    // Overwrite confirmation dialog (CreateEditScreen — Save with existing custom code)
    vdbOverwriteTitle = "Prepísať databázu?",
    vdbOverwriteDesc = "Vlastná databáza s kódom \"%s\" už existuje. Uloženie natrvalo prepíše jej verše. Túto akciu nie je možné vrátiť späť.",
    vdbOverwriteConfirm = "Prepísať",

    // --- Share verse as image ---
    share = "Zdieľať",
    shareDialogTitle = "Zdieľať verš",
    shareDialogDesc = "Vyberte akciu",
    shareAction = "Zdieľať",
    shareActionDesc = "Poslať obrázok cez iné aplikácie",
    saveToGalleryAction = "Uložiť do galérie",
    saveToGalleryActionDesc = "Uložiť obrázok do zariadenia",
    shareSuccess = "Verš zdieľaný",
    shareFailed = "Nepodarilo sa zdieľať verš",
    saveSuccess = "Verš uložený do galérie",
    saveFailed = "Nepodarilo sa uložiť do galérie",
    shareImageDesc = "Obrázok s veršom na zdieľanie",

    // --- Favorite verses ---
    favorites = "Obľúbené",
    favoritesTitle = "Obľúbené verše",
    favoritesEmpty = "Zatiaľ nemáte žiadne obľúbené verše",
    favoritesEmptyDesc = "Pridajte verš kliknutím na hviezdičku v náhľade.",
    addToFavorites = "Pridať do obľúbených",
    removeFromFavorites = "Odstrániť z obľúbených",
    favoritesCount = "%d obľúbených",
    setAsWallpaper = "Nastaviť ako tapetu",
    confirmRemoveFavoriteTitle = "Odstrániť z obľúbených?",
    confirmRemoveFavoriteDesc = "Tento verš bude odstránený z vašich obľúbených.",
    addedToFavorites = "Verš pridaný do obľúbených",
    removedFromFavorites = "Verš odstránený z obľúbených",
    addedOn = "Pridané %s"
)