package com.daklok.biblelockscreen.strings

// czStrings -- auto-extracted from MainActivity.kt (original lines 560..779).
val czStrings = AppStrings().apply {
    updateTime = "Čas denní aktualizace"
    settings = "Nastavení aplikace"
    dailyWallpaper = "Denní změna tapety"
    active = "Aktivní (každý den v %s:00)"
    inactive = "Vypnuto"
    textCustomization = "Přizpůsobení textu"
    bold = "Tučné"
    shadow = "Stín"
    textSize = "Velikost písma"
    textWidth = "Šířka textu"
    textHeight = "Výška textu"
    textAlpha = "Průhlednost"
    bgBlur = "Rozmazání pozadí"
    bgDarknessLabel = "Ztmavení pozadí"
    anotherPhoto = "Jiná fotka"
    test = "Generovat"
    selectPhotoFirst = "Nejdříve vyber fotku"
    appearance = "Vzhled"
    system = "Systém"
    light = "Světlý"
    dark = "Tmavý"
    dynamicColor = "Material You (Barvy systému)"
    haptics = "Haptická odezva"
    hapticsDesc = "Vibrace při úpravě widgetu"
    support = "Podpora"
    supportDesc = "Pokud se ti aplikace líbí a chceš podpořit její vývoj, můžeš mi koupit kávu ☕"
    donate = "Přispět"

    close = "Zavřít"
    dragHint = "Potažením bodů změň velikost\nTahem ve středu widget přesuň"
    cancel = "Zrušit"
    done = "Hotovo"
    clickToSelect = "Klikni pro výběr fotky"
    loading = "Načítám verš..."
    appLanguage = "Jazyk aplikace"
    verseLanguage = "Jazyk veršů"
    language = "Jazyk"
    dailyWorkerOn = "Zapnuto!\nTapeta se změní zítra v %s:00."
    dailyWorkerOff = "Denní změna byla vypnuta."
    generating = "Tapeta se generuje..."
    fontModern = "Moderní"

    fontBook = "Knižní"
    fontMono = "Strojový"
    fontCursive = "Psaný"
    fontLight = "Tenký"
    fontCondensed = "Úzký"

    generatingBtn = "Generuje se..."
    tapToEdit = "Kliknutím upravíš polohu a velikost"
    batteryWarningTitle = "Upozornění na baterii"
    batteryWarningDesc = "Aby automatická změna tapety fungovala spolehlivě na pozadí, vypněte prosím optimalizaci baterie pro tuto aplikaci."
    batteryWarningButton = "Vypnout optimalizaci"
    customVerseTitle = "Vlastní text"
    customVerseHint = "Text verše..."
    customRefHint = "Souřadnice (např. Jan 3:16)"
    applyCustom = "Použít"
    autoWallpaper = "Automatická změna tapety"
    autoWallpaperIntervalLabel = "Interval změny"
    autoWallpaperEvery1h = "Každou hodinu"
    autoWallpaperEvery2h = "Každé 2 hodiny"
    autoWallpaperEvery3h = "Každé 3 hodiny"
    autoWallpaperEvery6h = "Každých 6 hodin"
    autoWallpaperEvery12h = "Každých 12 hodin"
    autoWallpaperEvery24h = "Každých 24 hodin (denně)"
    autoWallpaperOnScreenOff = "Při vypnutí obrazovky"
    autoWallpaperOnScreenOffDesc = "Verš se změní při každém zamknutí telefonu"
    autoWallpaperTimeLabel = "Čas denní změny"
    autoWallpaperActiveHourly = "Aktivní (každých %sh)"
    autoWallpaperActiveDaily = "Aktivní (denně v %s:00)"
    autoWallpaperActiveScreenOff = "Aktivní (při zamknutí)"
    autoWorkerOn = "Zapnuto! Tapeta se změní dle nastaveného intervalu."
    autoWorkerOff = "Automatická změna byla vypnuta."
    colorPickerTitle = "Vybrat barvu"
    colorPickerBrightness = "Jas"
    colorPickerVerseColor = "Barva verše"

    // Wallpaper target
    wallpaperTargetLabel = "Použít tapetu na"
    wallpaperTargetLock = "Zamčená"
    wallpaperTargetHome = "Domů"
    wallpaperTargetBoth= "Oboje"

    // Verse database section
    vdbTitle = "Databáze veršů"
    vdbSubtitle = "Vytvoř, importuj nebo exportuj kolekce"
    vdbManage = "Spravovat"
    vdbNewDatabase = "Nová databáze"
    vdbEditPrefix = "Upravit ·"
    vdbImportExport = "Import / Export"
    vdbCreateNew = "Vytvořit novou"
    vdbSectionCustom = "Vlastní"
    vdbSectionBuiltIn = "Vestavěná"
    vdbHint = "Klepněte na \u201ePoužít\u201c u vlastní databáze a nastavte ji jako aktivní zdroj veršů — nebo ji vyberte později v Nastavení → Jazyk veršů."
    vdbUse = "Použít"
    vdbUsed = "Aktivováno"
    vdbDeleteTitle = "Smazat"
    vdbDeleteText = "veršů bude trvale odstraněno."
    vdbDelete = "Smazat"
    vdbDeleted = "Smazáno"
    vdbVerses = "veršů"
    vdbCustomLabel = "Vlastní"
    vdbCodeLabel = "Kód"
    vdbCodePlaceholder = "např. KJV"
    vdbCodeHint = "Vyber v Nastavení → Jazyk veršů"
    vdbUpdate = "Aktualizovat"
    vdbSave = "Uložit"
    vdbNoVerses = "Žádné verše — klepni na + níže"
    vdbVersesFilled = "vyplněno"
    vdbVerse = "verš"
    vdbVersePlural = "veršů"
    vdbClearAll = "Vymazat vše"
    vdbNoVersesYet = "Zatím žádné verše"
    vdbAddFirstVerse = "Klepnutím na tlačítko níže přidáš první verš"
    vdbAddVerse = "Přidat verš"
    vdbVerseText = "Text verše"
    vdbReference = "Souřadnice"
    vdbReferencePlaceholder = "např. Jan 3:16"
    vdbVerseCard = "Verš"
    vdbUpdated = "Aktualizováno"
    vdbCreated = "Vytvořeno"
    vdbErrorCode = "Zadej kód databáze"
    vdbErrorVerse = "Přidej alespoň jeden verš"
    vdbErrorFailed = "Chyba"
    vdbImportTitle = "Import"
    vdbImportJson = "Importovat JSON soubor"
    vdbImportDesc = "Vyber verse .json ze zařízení"
    vdbBrowse = "Procházet"
    vdbImporting = "Importuji..."
    vdbImportCodeTitle = "Kód databáze"
    vdbImportCodeDesc = "Zadej krátký kód pro tuto databázi (např. KJV). Přepíše vestavěnou databázi, pokud se kód shoduje."
    vdbImport = "Importovat"
    vdbImportSuccess = "Importováno %d veršů jako"
    vdbImportFailed = "Import selhal"
    vdbExportCustom = "Export — Vlastní"
    vdbExportBuiltIn = "Export — Vestavěná"
    vdbExport = "Exportovat"
    vdbExporting = "Ukládám do Downloads…"
    vdbExportDone = "Uloženo do Downloads"
    vdbExportFailed = "Export selhal"
    vdbJsonFormat = "Formát JSON"

    // Backup & Restore
    backupTitle = "Záloha a obnova"
    backupExport = "Zálohovat nastavení"
    backupExportDesc = "Uloží všechna nastavení, tapetu a databáze do jednoho souboru"
    backupImport = "Obnovit ze zálohy"
    backupImportDesc = "Nahradí všechna aktuální nastavení, tapetu a databáze"
    backupExporting = "Zálohuji…"
    backupImporting = "Obnovuji…"
    backupExportSuccess = "Záloha uložena · %d nastavení, %d databází"
    backupImportSuccess = "Záloha obnovena · %d nastavení, %d databází. Restartuji…"
    backupExportFailed = "Záloha selhala"
    backupImportFailed = "Obnova selhala"
    backupConfirmTitle = "Obnovit ze zálohy?"
    backupConfirmDesc = "Toto nahradí všechna tvá aktuální nastavení, tapetu a databáze. Akci nelze vrátit zpět."

    // Wallpaper gallery screen
    wpScreenTitle = "Tapety"
    wpScreenSubtitle = "Spravuj své tapety a automatické střídání"
    wpGalleryEmpty = "Žádné tapety"
    wpGalleryEmptyDesc = "Přidej svou první tapetu — vyber fotku z galerie."
    wpAdd = "Přidat tapetu"
    wpSetActive = "Použít"
    wpActive = "Aktivní"
    wpDelete = "Odstranit"
    wpDeleteConfirm = "Odstranit tuto tapetu?"
    wpDeleteConfirmDesc = "Tapeta bude trvale odstraněna z aplikace."
    wpCycleTitle = "Automatické střídání"
    wpCycleDesc = "Strídej tapety automaticky podle intervalu"
    wpCycleInterval = "Interval střídání"
    wpCycleDailyHour = "Čas denní změny"
    wpCycleOnScreenOff = "Při zamčení"
    wpCycleOnScreenOffDesc = "Změní tapetu při každém zamčení telefonu"
    wpNightMode = "Noční režim"
    wpNightModeDesc = "Použít jinou tapetu v noci"
    wpNightStart = "Začátek noci"
    wpNightEnd = "Konec noci"
    wpActiveBadge = "Aktivní"
    wpNightBadge = "Noční"
    wpCycleModeVerse = "Při změně verše"
    wpCycleModeInterval = "Vlastní interval"
    wpCycleModeScreenOff = "Při zamčení"
    wpCycleModeDayNight = "Den / Noc"
    wpCycleModeVerseDesc = "Tapeta se změní spolu s veršem"
    wpCycleModeDayNightDesc = "Automaticky přepínat mezi denní a noční tapetou"
    wpCycleDayWallpaper = "Denní tapeta"
    wpCycleNightWallpaper = "Noční tapeta"
    wpCycleModeIntervalDesc = "Změna v pevných intervalech"
    wpCycleModeScreenOffDesc = "Změna při každém zamčení"
    wpDualLockWarning = "Změna tapety při vypnutém displeji může trvat až 3 sekundy."
    wpDayStart = "Začátek dne"
    wpDayEnd = "Konec dne"

    wpViewAll = "Zobrazit vše"
    wpViewAllTitle = "Všechny tapety"
    wpSelectMode = "Vybrat"
    wpDeleteSelected = "Smazat vybrané"
    wpSelected = "vybraných"
    wpDeleteAllConfirm = "Smazat vybrané tapety?"
    wpDeleteAllConfirmDesc = "Vybrané tapety budou trvale odstraněny z aplikace."
    wpPageHint = "Potáhni doleva pro tapety →"

    // Verse language source toggle (in Settings)
    vdbSourceDefault = "Vestavěné"
    vdbSourceCustom = "Vlastní"
    vdbSourceFavorites = "Oblíbené"
    vdbFavoritesCycling = "Střídání %d oblíbených veršů"
    vdbFavoritesEmptyCta = "Nejdřív přidej nějaké oblíbené"
    vdbEmptyCustom = "Zatím žádné vlastní databáze"
    vdbEmptyCustomDesc = "Vytvoř si vlastní sbírku veršů — třeba pro KJV nebo jiný překlad."
    vdbEmptyCustomCta = "Vytvořit novou databázi"

    // Duplicate-code warnings + import conflict dialog
    vdbWarningCodeBuiltin = "Kód \"%s\" je již použit vestavěnou databází. Můžeš ho použít — vlastní DB bude sdílet kód."
    vdbWarningCodeCustom = "Kód \"%s\" již existuje jako vlastní databáze. Uložení ji přepíše."
    vdbImportConflictTitle = "Kód již existuje"
    vdbImportConflictDesc = "Vlastní databáze s kódem \"%s\" již existuje. Zadej jiný kód, nebo nech \"%s\" pro přepsání."
    vdbImportConflictAction = "Importovat s tímto kódem"

    // Overwrite confirmation dialog (CreateEditScreen — Save with existing custom code)
    vdbOverwriteTitle = "Přepsat databázi?"
    vdbOverwriteDesc = "Vlastní databáze s kódem \"%s\" již existuje. Uložení trvale přepíše její verše. Tuto akci nelze vrátit zpět."
    vdbOverwriteConfirm = "Přepsat"
    share = "Sdílet"
    shareDialogTitle = "Sdílet verš"
    shareDialogDesc = "Vyberte akci"
    shareAction = "Sdílet"
    shareActionDesc = "Odeslat obrázek přes jiné aplikace"
    saveToGalleryAction = "Uložit do galerie"
    saveToGalleryActionDesc = "Uložit obrázek do zařízení"
    shareSuccess = "Verš sdílen"
    shareFailed = "Nepodařilo se sdílet verš"
    saveSuccess = "Verš uložen do galerie"
    saveFailed = "Nepodařilo se uložit do galerie"
    shareImageDesc = "Obrázek s veršem pro sdílení"

    // --- Favorite verses ---
    favorites = "Oblíbené"
    favoritesTitle = "Oblíbené verše"
    favoritesEmpty = "Zatím nemáte žádné oblíbené verše"
    favoritesEmptyDesc = "Přidejte verš klepnutím na hvězdičku v náhledu."
    addToFavorites = "Přidat do oblíbených"
    removeFromFavorites = "Odebrat z oblíbených"
    favoritesCount = "%d oblíbených"
    setAsWallpaper = "Nastavit jako tapetu"
    confirmRemoveFavoriteTitle = "Odebrat z oblíbených?"
    confirmRemoveFavoriteDesc = "Tento verš bude odebrán z vašich oblíbených."
    addedToFavorites = "Verš přidán do oblíbených"
    removedFromFavorites = "Verš odebrán z oblíbených"
    addedOn = "Přidáno %s"
    favoritesSubtitle = "Klepnutím na verš ho nastavíte jako tapetu"
    favCardStyleLabel = "Styl karty oblíbených"
    favCardStyleQuote = "Detailní"
    favCardStyleCompact = "Kompaktní"
    favCardStyleHero = "Citát"
    favCardStyleQuoteDesc = "Verš s panelem akcí"
    favCardStyleCompactDesc = "Kompaktní řádek"
    favCardStyleHeroDesc = "Velký citát jako plakát"

    // --- Credits ---
    creditsTitle = "Poděkování"
    creditsTranslatorsLabel = "Překladatelé"
    creditsDeveloperDesc = "Vývojář · původní texty rozhraní a verše"
    creditsTranslatorZhDesc = "Překlad do zjednodušené čínštiny (简体中文)"
    creditsViewOnGithub = "Zobrazit na GitHubu"

    // Interactive walkthrough tutorial (TutorialScreen.kt)
    tutorialSkip = "Přeskočit"
    tutorialNext = "Další"
    tutorialGetStarted = "Jdeme na to"
    tutorialStartTour = "Spustit prohlídku"
    tutorialStepOf = "Krok %1\$d z %2\$d"
    tutorialTapHint = "Klepni na zvýrazněnou oblast a pokračuj"
    tutorialSwipeHint = "Přejeď prstem doleva a pokračuj"
    tutorialScrollHint = "Posuň se dolů a pokračuj"
    tutorialTitleWelcome = "Vítej v Bible Lock Screen"
    tutorialDescWelcome = "Projděme si aplikaci společně, přesně ti ukážu, kam klepnout a čím přejet. Trvá to jen minutu."
    tutorialTitlePreview = "Toto je tvoja zamčená obrazovka"
    tutorialDescPreview = "Živý náhled tvojí tapety a verše, přesně tak, jak se zobrazí na zamčené obrazovce."
    tutorialTitlePickPhoto = "Vyber fotku"
    tutorialDescPickPhoto = "Klepni na náhled a vyber si fotku na pozadí z galerie. Tak do toho, zkus to hned!"
    tutorialTitleGenerate = "Nastav si tapetu"
    tutorialDescGenerate = "Stiskni Generovat a verš se ti použije na fotku a nastaví se jako tapeta na zamčené obrazovce."
    tutorialTitleNoPhoto = "Nejdřív vyber fotku"
    tutorialDescNoPhoto = "Jakmile si vybereš fotku, nastavení verše i tlačítko Generovat se objeví hned pod náhledem."
    tutorialTitleVerseSettings = "Tady najdeš nastavení verše"
    tutorialDescVerseSettings = "Uprav si verš (velikost, barvu, písmo, polohu) nebo si napiš vlastní. Projdi celý panel a prohlédni si všechno."
    tutorialTitleEditor = "Editor na celou obrazovku"
    tutorialDescEditor = "Klepni na verš v náhledu a otevře se editor na celou obrazovku, ve kterém verš přesuneš přesně tam, kam chceš."
    tutorialTitleVerseCycling = "Verše se můžou měnit i samy"
    tutorialDescVerseCycling = "Zapni tohle a nový verš se ti vybere sám: denně v nastavený čas, každých pár hodin nebo při každém odemknutí."
    tutorialTitleSwipeWallpapers = "Otevři správu tapet"
    tutorialDescSwipeWallpapers = "Přejeď prstem doleva, nebo klepni na jednu z teček, a stránka se přepne."
    tutorialTitleWallpaperManager = "Tvoje sbírka tapet"
    tutorialDescWallpaperManager = "Všechny tvoje tapety jsou tady. Přidávej fotky, jednu klepnutím aktivuj nebo smaž ty, které nepotřebuješ."
    tutorialTitleWallpaperCycling = "Tapety se mění samostatně"
    tutorialDescWallpaperCycling = "Tady se tapety střídají podle vlastního rozvrhu, nezávisle na verších. Dokud je to vypnuté, mění se tapeta spolu s veršem."
    tutorialTitleSwipeFavorites = "Ještě jedno přejetí"
    tutorialDescSwipeFavorites = "Přejeď prstem doleva ještě jednou a dostaneš se k oblíbeným veršům."
    tutorialTitleFavorites = "Schovávej si verše, které miluješ"
    tutorialDescFavorites = "Klepnutím na srdíčko v náhledu si verš uložíš sem. Oblíbený verš zase nastav jako tapetu nebo ho sdílej jako obrázek."
    tutorialTitleAppSettings = "Zbytek v Nastavení aplikace"
    tutorialDescAppSettings = "Klepni na ozubené kolo a najdeš motivy, jazyky, zálohu a další. Rozhlédni se, prohlídka pokračuje, jakmile je zavřeš."
    tutorialTitleDone = "Všechno máš připravené!"
    tutorialDescDone = "To je celá prohlídka a teď se v aplikaci už vyznáš. Kdykoli si ji můžeš zopakovat v Nastavení aplikace."
    tutorialReplayTitle = "Zobrazit tutoriál znovu"
    tutorialReplayDesc = "Zopakuj si interaktivní prohlídku funkcí aplikace"
}

// Localized language names in Czech (top-level, see AppStrings.kt for why).
val czLocalizedLangNames: Map<String, String> = mapOf(
    "EN" to "Angličtina",
    "SK" to "Slovenština",
    "CZ" to "Čeština",
    "ES" to "Španělština",
    "IT" to "Italština",
    "FR" to "Francouzština",
    "DE" to "Němčina",
    "HU" to "Maďarština",
    "PL" to "Polština",
    "ZH" to "简体中文"
)
