package com.daklok.biblelockscreen.strings

// itStrings -- auto-extracted from MainActivity.kt (original lines 1002..1221).
val itStrings = AppStrings().apply {
    updateTime = "Ora della modifica giornaliera"
    settings = "Impostazioni App"
    dailyWallpaper = "Sfondo giornaliero"
    active = "Attivo (ogni giorno alle %s:00)"
    inactive = "Inattivo"
    textCustomization = "Personalizzazione testo"
    bold = "Grassetto"
    shadow = "Ombra"
    textSize = "Dimensione testo"
    textWidth = "Larghezza testo"
    textHeight = "Altezza testo"
    textAlpha = "Trasparenza"
    bgBlur = "Sfocatura sfondo"
    bgDarknessLabel = "Oscuramento dello sfondo"
    anotherPhoto = "Cambia foto"
    test = "Generare"
    selectPhotoFirst = "Seleziona prima una foto"
    appearance = "Aspetto"
    system = "Sistema"
    light = "Chiaro"
    dark = "Scuro"
    dynamicColor = "Material You (Colori di sistema)"
    haptics = "Feedback tattile"
    hapticsDesc = "Vibrazioni durante la modifica"
    support = "Supporto"
    supportDesc = "Se ti piace l'app e vuoi supportarne lo sviluppo, puoi offrirmi un caffè ☕"
    donate = "Dona"

    close = "Chiudi"
    dragHint = "Trascina i punti per la dimensione e la larghezza\nTrascina al centro per spostare"
    cancel = "Annulla"
    done = "Fatto"
    clickToSelect = "Tocca per selezionare una foto"
    loading = "Caricamento versetto..."
    appLanguage = "Lingua dell'app"
    verseLanguage = "Lingua del versetto"
    language = "Lingua"
    dailyWorkerOn = "Attivato!\nLo sfondo cambierà domani alle %s:00."
    dailyWorkerOff = "Cambio giornaliero disattivato."
    generating = "Generazione sfondo..."

    fontModern = "Moderno"
    fontBook = "Libro"
    fontMono = "Macchina da scrivere"
    fontCursive = "Corsivo"
    fontLight = "Sottile"
    fontCondensed = "Condensato"

    generatingBtn = "Generazione..."
    tapToEdit = "Tocca per cambiare posizione e dimensione"
    batteryWarningTitle = "Avviso Batteria"
    batteryWarningDesc = "Affinché il cambio automatico dello sfondo funzioni in modo affidabile, disabilita l'ottimizzazione della batteria per questa app."
    batteryWarningButton = "Disabilita Ottimizzazione"
    customVerseTitle = "Testo Personalizzato"
    customVerseHint = "Testo del versetto..."
    customRefHint = "Coordinate (es. Giovanni 3:16)"
    applyCustom = "Applica"
    autoWallpaper = "Cambio automatico sfondo"
    autoWallpaperIntervalLabel = "Intervallo di cambio"
    autoWallpaperEvery1h = "Ogni ora"
    autoWallpaperEvery2h = "Ogni 2 ore"
    autoWallpaperEvery3h = "Ogni 3 ore"
    autoWallpaperEvery6h = "Ogni 6 ore"
    autoWallpaperEvery12h = "Ogni 12 ore"
    autoWallpaperEvery24h = "Ogni 24 ore (giornaliero)"
    autoWallpaperOnScreenOff = "Allo spegnimento schermo"
    autoWallpaperOnScreenOffDesc = "Il versetto cambia ogni volta che blocchi il telefono"
    autoWallpaperTimeLabel = "Orario cambio giornaliero"
    autoWallpaperActiveHourly = "Attivo (ogni %sh)"
    autoWallpaperActiveDaily = "Attivo (giornaliero alle %s:00)"
    autoWallpaperActiveScreenOff = "Attivo (al blocco)"
    autoWorkerOn = "Attivato! Lo sfondo cambierà in base all'intervallo impostato."
    autoWorkerOff = "Cambio automatico disattivato."
    colorPickerTitle = "Seleziona colore"
    colorPickerBrightness = "Luminosità"
    colorPickerVerseColor = "Colore del versetto"

    // Wallpaper target
    wallpaperTargetLabel = "Applica sfondo su"
    wallpaperTargetLock = "Blocco"
    wallpaperTargetHome = "Home"
    wallpaperTargetBoth = "Entrambi"

    // Verse database section
    vdbTitle = "Database di versetti"
    vdbSubtitle = "Crea, importa o esporta raccolte"
    vdbManage = "Gestisci"
    vdbNewDatabase = "Nuovo database"
    vdbEditPrefix = "Modifica ·"
    vdbImportExport = "Importa / Esporta"
    vdbCreateNew = "Crea nuovo"
    vdbSectionCustom = "Personalizzato"
    vdbSectionBuiltIn = "Integrato"
    vdbHint = "Tocca \u00abUsa\u00bb su un database personalizzato per renderlo la tua fonte attiva dei versetti — o selezionalo più tardi in Impostazioni → Lingua versetti."
    vdbUse = "Usa"
    vdbUsed = "Attivato"
    vdbDeleteTitle = "Elimina"
    vdbDeleteText = "versetti saranno eliminati definitivamente."
    vdbDelete = "Elimina"
    vdbDeleted = "Eliminato"
    vdbVerses = "versetti"
    vdbCustomLabel = "Personalizzato"
    vdbCodeLabel = "Codice"
    vdbCodePlaceholder = "es. CEI"
    vdbCodeHint = "Selezionalo in Impostazioni → Lingua versetti"
    vdbUpdate = "Aggiorna"
    vdbSave = "Salva"
    vdbNoVerses = "Nessun versetto — tocca + in basso"
    vdbVersesFilled = "compilati"
    vdbVerse = "versetto"
    vdbVersePlural = "versetti"
    vdbClearAll = "Cancella tutto"
    vdbNoVersesYet = "Ancora nessun versetto"
    vdbAddFirstVerse = "Tocca il pulsante in basso per aggiungere il primo versetto"
    vdbAddVerse = "Aggiungi versetto"
    vdbVerseText = "Testo del versetto"
    vdbReference = "Riferimento"
    vdbReferencePlaceholder = "es. Giovanni 3:16"
    vdbVerseCard = "Versetto"
    vdbUpdated = "Aggiornato"
    vdbCreated = "Creato"
    vdbErrorCode = "Inserisci un codice per il database"
    vdbErrorVerse = "Aggiungi almeno un versetto"
    vdbErrorFailed = "Errore"
    vdbImportTitle = "Importa"
    vdbImportJson = "Importa file JSON"
    vdbImportDesc = "Scegli un .json di versetti dal dispositivo"
    vdbBrowse = "Sfoglia"
    vdbImporting = "Importazione..."
    vdbImportCodeTitle = "Codice database"
    vdbImportCodeDesc = "Inserisci un codice breve per questo database (es. CEI). Sostituisce il database integrato se il codice corrisponde."
    vdbImport = "Importa"
    vdbImportSuccess = "Importati %d versetti come"
    vdbImportFailed = "Importazione fallita"
    vdbExportCustom = "Esporta — Personalizzato"
    vdbExportBuiltIn = "Esporta — Integrato"
    vdbExport = "Esporta"
    vdbExporting = "Salvataggio in Download…"
    vdbExportDone = "Salvato in Download"
    vdbExportFailed = "Esportazione fallita"
    vdbJsonFormat = "Formato JSON"

    // Backup & Restore
    backupTitle = "Backup e ripristino"
    backupExport = "Esegui backup delle impostazioni"
    backupExportDesc = "Salva tutte le impostazioni, lo sfondo e i database in un unico file"
    backupImport = "Ripristina da backup"
    backupImportDesc = "Sostituisce tutte le impostazioni, lo sfondo e i database attuali"
    backupExporting = "Backup in corso…"
    backupImporting = "Ripristino in corso…"
    backupExportSuccess = "Backup salvato · %d impostazioni, %d database"
    backupImportSuccess = "Backup ripristinato · %d impostazioni, %d database. Riavvio…"
    backupExportFailed = "Backup fallito"
    backupImportFailed = "Ripristino fallito"
    backupConfirmTitle = "Ripristinare dal backup?"
    backupConfirmDesc = "Verranno sostituite tutte le impostazioni, lo sfondo e i database attuali. Operazione irreversibile."

    // Wallpaper gallery screen
    wpScreenTitle = "Sfondi"
    wpScreenSubtitle = "Gestisci i tuoi sfondi e la rotazione automatica"
    wpGalleryEmpty = "Nessuno sfondo"
    wpGalleryEmptyDesc = "Aggiungi il tuo primo sfondo — scegli una foto dalla galleria."
    wpAdd = "Aggiungi sfondo"
    wpSetActive = "Usa"
    wpActive = "Attivo"
    wpDelete = "Rimuovi"
    wpDeleteConfirm = "Rimuovere questo sfondo?"
    wpDeleteConfirmDesc = "Lo sfondo verrà rimosso definitivamente dall'app."
    wpCycleTitle = "Rotazione automatica"
    wpCycleDesc = "Cambia sfondo automaticamente secondo un intervallo"
    wpCycleInterval = "Intervallo di rotazione"
    wpCycleDailyHour = "Ora cambio giornaliero"
    wpCycleOnScreenOff = "Al blocco"
    wpCycleOnScreenOffDesc = "Cambia sfondo ogni volta che blocchi il telefono"
    wpNightMode = "Modalità notturna"
    wpNightModeDesc = "Usa uno sfondo diverso di notte"
    wpNightStart = "Inizio notte"
    wpNightEnd = "Fine notte"
    wpActiveBadge = "Attivo"
    wpNightBadge = "Notte"
    wpCycleModeVerse = "Al cambio versetto"
    wpCycleModeInterval = "Intervallo personalizzato"
    wpCycleModeScreenOff = "Ad ogni blocco"
    wpCycleModeDayNight = "Giorno / Notte"
    wpCycleModeVerseDesc = "Lo sfondo cambia con il versetto"
    wpCycleModeDayNightDesc = "Cambia automaticamente tra sfondo di giorno e di notte"
    wpCycleDayWallpaper = "Sfondo di giorno"
    wpCycleNightWallpaper = "Sfondo di notte"
    wpCycleModeIntervalDesc = "Cambia a intervalli fissi"
    wpCycleModeScreenOffDesc = "Cambia ad ogni blocco"
    wpDualLockWarning = "Il cambio sfondo a schermo spento può richiedere fino a 3 secondi."
    wpDayStart = "Il giorno inizia"
    wpDayEnd = "Il giorno finisce"

    wpViewAll = "Vedi tutti"
    wpViewAllTitle = "Tutti gli sfondi"
    wpSelectMode = "Seleziona"
    wpDeleteSelected = "Elimina selezionati"
    wpSelected = "selezionati"
    wpDeleteAllConfirm = "Eliminare gli sfondi selezionati?"
    wpDeleteAllConfirmDesc = "Gli sfondi selezionati verranno rimossi definitivamente dall'app."
    wpPageHint = "Scorri a sinistra per gli sfondi →"

    // Verse language source toggle (in Settings)
    vdbSourceDefault = "Predefinite"
    vdbSourceCustom = "Personalizzate"
    vdbSourceFavorites = "Preferiti"
    vdbFavoritesCycling = "Ciclo tra %d versetti preferiti"
    vdbFavoritesEmptyCta = "Aggiungi prima dei preferiti"
    vdbEmptyCustom = "Nessun database personalizzato"
    vdbEmptyCustomDesc = "Crea la tua raccolta di versetti, ad esempio KJV o un'altra traduzione."
    vdbEmptyCustomCta = "Crea nuovo database"

    // Duplicate-code warnings + import conflict dialog
    vdbWarningCodeBuiltin = "Il codice \"%s\" è già usato da un database integrato. Puoi comunque usarlo — il database personalizzato condividerà il codice."
    vdbWarningCodeCustom = "Il codice \"%s\" esiste già come database personalizzato. Il salvataggio lo sovrascriverà."
    vdbImportConflictTitle = "Codice già esistente"
    vdbImportConflictDesc = "Esiste già un database personalizzato con codice \"%s\". Inserisci un codice diverso, oppure lascia \"%s\" per sovrascrivere."
    vdbImportConflictAction = "Importa con questo codice"

    // Overwrite confirmation dialog (CreateEditScreen — Save with existing custom code)
    vdbOverwriteTitle = "Sovrascrivere il database?"
    vdbOverwriteDesc = "Esiste già un database personalizzato con codice \"%s\". Il salvataggio sostituirà definitivamente i suoi versetti. Questa azione non può essere annullata."
    vdbOverwriteConfirm = "Sovrascrivi"
    share = "Condividi"
    shareDialogTitle = "Condividi versetto"
    shareDialogDesc = "Scegli un'azione"
    shareAction = "Condividi"
    shareActionDesc = "Invia l'immagine tramite altre app"
    saveToGalleryAction = "Salva in galleria"
    saveToGalleryActionDesc = "Salva l'immagine sul dispositivo"
    shareSuccess = "Versetto condiviso"
    shareFailed = "Condivisione fallita"
    saveSuccess = "Versetto salvato in galleria"
    saveFailed = "Salvataggio fallito"
    shareImageDesc = "Immagine con versetto da condividere"

    // --- Favorite verses ---
    favorites = "Preferiti"
    favoritesTitle = "Versetti preferiti"
    favoritesEmpty = "Non hai ancora versetti preferiti"
    favoritesEmptyDesc = "Aggiungi un versetto toccando la stella nell'anteprima."
    addToFavorites = "Aggiungi ai preferiti"
    removeFromFavorites = "Rimuovi dai preferiti"
    favoritesCount = "%d preferiti"
    setAsWallpaper = "Imposta come sfondo"
    confirmRemoveFavoriteTitle = "Rimuovere dai preferiti?"
    confirmRemoveFavoriteDesc = "Questo versetto verrà rimosso dai tuoi preferiti."
    addedToFavorites = "Versetto aggiunto ai preferiti"
    removedFromFavorites = "Versetto rimosso dai preferiti"
    addedOn = "Aggiunto %s"
    favoritesSubtitle = "Tocca un versetto per impostarlo come sfondo"
    favCardStyleLabel = "Stile scheda preferiti"
    favCardStyleQuote = "Dettagliato"
    favCardStyleCompact = "Compatto"
    favCardStyleHero = "Citazione"
    favCardStyleQuoteDesc = "Versetto con barra azioni"
    favCardStyleCompactDesc = "Riga compatta"
    favCardStyleHeroDesc = "Citazione grande come poster"

}

// Localized language names in Italian (top-level, see AppStrings.kt for why).
val itLocalizedLangNames: Map<String, String> = mapOf(
    "EN" to "Inglese",
    "SK" to "Slovacco",
    "CZ" to "Ceco",
    "ES" to "Spagnolo",
    "IT" to "Italiano",
    "FR" to "Francese",
    "DE" to "Tedesco",
    "HU" to "Ungherese",
    "PL" to "Polacco"
)
