package com.daklok.biblelockscreen.strings

// =============================================================================
// Simplified Chinese (ZH) translation — 简体中文翻译
//
// Generated from StringsTemplate.kt.txt. Every entry corresponds to an English
// default declared in AppStrings.kt; any field left out falls back to English.
//
// Verse content: app/src/main/assets/verses_ZH.json
//   Bible version: 和合本 (Chinese Union Version, 1919) — public domain.
// =============================================================================

val zhStrings = AppStrings().apply {

    test = "生成"
    generatingBtn = "生成中…"
    generating = "正在生成壁纸…"
    done = "完成"
    updateTime = "每日更新时间"
    tapToEdit = "点按以调整位置和大小"
    appName = "圣经锁屏"
    settings = "应用设置"
    dailyWallpaper = "每日更换壁纸"
    active = "已启用（每天 %s:00）"
    inactive = "已停用"
    textCustomization = "文字自定义"
    bold = "加粗"
    shadow = "阴影"
    textSize = "文字大小"
    textWidth = "文字宽度"
    textHeight = "文字位置"
    textAlpha = "透明度"
    bgBlur = "背景模糊"
    bgDarknessLabel = "背景明暗"
    anotherPhoto = "更换照片"
    selectPhotoFirst = "请先选择一张照片"
    appearance = "外观"
    system = "跟随系统"
    light = "浅色"
    dark = "深色"
    dynamicColor = "Material You（系统配色）"
    haptics = "触感反馈"
    hapticsDesc = "编辑挂件时振动"
    support = "支持"
    supportDesc = "如果你喜欢这款应用并希望支持它的开发，可以请我喝杯咖啡 ☕"
    donate = "捐赠"
    close = "关闭"
    dragHint = "拖动圆点调整大小和宽度\n拖动中心以移动"
    cancel = "取消"
    clickToSelect = "点按选择照片"
    loading = "正在加载经文…"
    appLanguage = "应用语言"
    verseLanguage = "经文语言"
    language = "语言"
    dailyWorkerOn = "已启用！\n壁纸将在明天 %s:00 更换。"
    dailyWorkerOff = "已停用每日更换。"
    fontModern = "现代"
    fontBook = "书体"
    fontMono = "打字机"
    fontCursive = "手写"
    fontLight = "细体"
    fontCondensed = "紧凑"
    langSk = "Slovenčina"
    langEn = "English"
    langCz = "Čeština"
    batteryWarningTitle = "电池警告"
    batteryWarningDesc = "为保证自动更换壁纸能在后台可靠运行，请为本应用关闭电池优化。"
    batteryWarningButton = "关闭电池优化"
    customVerseTitle = "自定义文字"
    customVerseHint = "经文内容…"
    customRefHint = "出处（例如 约3:16）"
    applyCustom = "应用"
    autoWallpaper = "自动更换壁纸"
    autoWallpaperIntervalLabel = "更换间隔"
    autoWallpaperEvery1h = "每小时"
    autoWallpaperEvery2h = "每 2 小时"
    autoWallpaperEvery3h = "每 3 小时"
    autoWallpaperEvery6h = "每 6 小时"
    autoWallpaperEvery12h = "每 12 小时"
    autoWallpaperEvery24h = "每 24 小时（每天）"
    autoWallpaperOnScreenOff = "熄屏时"
    autoWallpaperOnScreenOffDesc = "每次锁屏时更换经文"
    autoWallpaperTimeLabel = "每日更换时间"
    autoWallpaperActiveHourly = "已启用（每 %s 小时）"
    autoWallpaperActiveDaily = "已启用（每天 %s:00）"
    autoWallpaperActiveScreenOff = "已启用（锁屏时）"
    autoWorkerOn = "已启用！壁纸将按你设置的间隔更换。"
    autoWorkerOff = "已停用自动更换。"
    colorPickerTitle = "选择颜色"
    colorPickerBrightness = "亮度"
    colorPickerVerseColor = "经文颜色"
    wallpaperTargetLabel = "壁纸应用到"
    wallpaperTargetLock = "锁屏"
    wallpaperTargetHome = "主屏幕"
    wallpaperTargetBoth = "两者"
    vdbTitle = "经文数据库"
    vdbSubtitle = "创建、导入或导出经文集合"
    vdbManage = "管理"
    vdbNewDatabase = "新建数据库"
    vdbEditPrefix = "编辑 ·"
    vdbImportExport = "导入 / 导出"
    vdbCreateNew = "新建"
    vdbSectionCustom = "自定义"
    vdbSectionBuiltIn = "内置"
    vdbHint = "点按自定义数据库上的「使用」，即可将其设为当前经文来源——也可以稍后在 设置 → 经文语言 中选择。"
    vdbUse = "使用"
    vdbUsed = "已启用"
    vdbDeleteTitle = "删除"
    vdbDeleteText = "节经文将被永久删除。"
    vdbDelete = "删除"
    vdbDeleted = "已删除"
    vdbVerses = "节经文"
    vdbCustomLabel = "自定义"
    vdbCodeLabel = "代码"
    vdbCodePlaceholder = "例如 KJV"
    vdbCodeHint = "在 设置 → 经文语言 中选择此项"
    vdbUpdate = "更新"
    vdbSave = "保存"
    vdbNoVerses = "暂无经文——点按下方 + 添加"
    vdbVersesFilled = "已填写"
    vdbVerse = "节经文"
    vdbVersePlural = "节经文"
    vdbClearAll = "全部清除"
    vdbNoVersesYet = "还没有经文"
    vdbAddFirstVerse = "点按下方按钮添加第一节经文"
    vdbAddVerse = "添加经文"
    vdbVerseText = "经文内容"
    vdbReference = "出处"
    vdbReferencePlaceholder = "例如 约3:16"
    vdbVerseCard = "经文"
    vdbUpdated = "已更新"
    vdbCreated = "已创建"
    vdbErrorCode = "请输入数据库代码"
    vdbErrorVerse = "请至少添加一节经文"
    vdbErrorFailed = "失败"
    vdbImportTitle = "导入"
    vdbImportJson = "导入 JSON 文件"
    vdbImportDesc = "从设备中选择一个经文 .json 文件"
    vdbBrowse = "浏览"
    vdbImporting = "导入中…"
    vdbImportCodeTitle = "数据库代码"
    vdbImportCodeDesc = "为该数据库输入一个简短代码（例如 KJV）。若代码与内置数据库相同，将覆盖该内置数据库。"
    vdbImport = "导入"
    vdbImportSuccess = "已导入 %d 节经文，代码为"
    vdbImportFailed = "导入失败"
    vdbExportCustom = "导出 — 自定义"
    vdbExportBuiltIn = "导出 — 内置"
    vdbExport = "导出"
    vdbExporting = "正在保存到「下载」…"
    vdbExportDone = "已保存到「下载」"
    vdbExportFailed = "导出失败"
    vdbJsonFormat = "JSON 格式"
    backupTitle = "备份与恢复"
    backupExport = "备份设置"
    backupExportDesc = "将所有设置、壁纸和数据库保存到一个文件"
    backupImport = "从备份恢复"
    backupImportDesc = "替换当前所有设置、壁纸和数据库"
    backupExporting = "正在备份…"
    backupImporting = "正在恢复…"
    backupExportSuccess = "备份已保存 · %d 项设置，%d 个数据库"
    backupImportSuccess = "备份已恢复 · %d 项设置，%d 个数据库。正在重启…"
    backupExportFailed = "备份失败"
    backupImportFailed = "恢复失败"
    backupConfirmTitle = "从备份恢复？"
    backupConfirmDesc = "这将替换你当前的所有设置、壁纸和数据库，且无法撤销。"
    wpScreenTitle = "壁纸"
    wpScreenSubtitle = "管理你的壁纸和自动轮换"
    wpGalleryEmpty = "没有壁纸"
    wpGalleryEmptyDesc = "添加你的第一张壁纸——从相册中选择一张照片。"
    wpAdd = "添加壁纸"
    wpSetActive = "设为当前"
    wpActive = "当前"
    wpDelete = "移除"
    wpDeleteConfirm = "移除这张壁纸？"
    wpDeleteConfirmDesc = "该壁纸将从应用中永久移除。"
    wpCycleTitle = "自动轮换"
    wpCycleDesc = "按计划自动轮换壁纸"
    wpCycleInterval = "轮换间隔"
    wpCycleDailyHour = "每日更换时间"
    wpCycleOnScreenOff = "锁屏时"
    wpCycleOnScreenOffDesc = "每次锁屏时更换壁纸"
    wpNightMode = "夜间模式"
    wpNightModeDesc = "夜间使用不同的壁纸"
    wpNightStart = "夜间开始"
    wpNightEnd = "夜间结束"
    wpActiveBadge = "当前"
    wpNightBadge = "夜间"
    wpCycleModeVerse = "经文更换时"
    wpCycleModeInterval = "自定义间隔"
    wpCycleModeScreenOff = "每次锁屏时"
    wpCycleModeDayNight = "白天 / 夜间"
    wpCycleModeVerseDesc = "壁纸随经文一同更换"
    wpCycleModeDayNightDesc = "在白天和夜间壁纸之间自动切换"
    wpCycleDayWallpaper = "白天壁纸"
    wpCycleNightWallpaper = "夜间壁纸"
    wpCycleModeIntervalDesc = "按固定间隔更换"
    wpCycleModeScreenOffDesc = "每次锁屏时更换"
    wpDualLockWarning = "熄屏时更新壁纸最多可能需要 3 秒。"
    wpDayStart = "白天开始"
    wpDayEnd = "白天结束"
    wpViewAll = "查看全部"
    wpViewAllTitle = "全部壁纸"
    wpSelectMode = "选择"
    wpDeleteSelected = "删除所选"
    wpSelected = "已选择"
    wpDeleteAllConfirm = "删除所选壁纸？"
    wpDeleteAllConfirmDesc = "所选的壁纸将从应用中永久移除。"
    wpPageHint = "向左滑动查看壁纸 →"
    vdbSourceDefault = "默认"
    vdbSourceCustom = "自定义"
    vdbSourceFavorites = "收藏"
    vdbFavoritesCycling = "在 %d 节收藏经文中轮换"
    vdbFavoritesEmptyCta = "请先添加一些收藏"
    vdbEmptyCustom = "还没有自定义数据库"
    vdbEmptyCustomDesc = "创建你自己的经文集合——例如 KJV 或其他译本。"
    vdbEmptyCustomCta = "新建数据库"
    vdbWarningCodeBuiltin = "代码「%s」已被某个内置数据库占用。你仍然可以使用它——自定义数据库将与该内置数据库共用此代码。"
    vdbWarningCodeCustom = "代码「%s」已作为自定义数据库存在。保存将覆盖它。"
    vdbImportConflictTitle = "代码已存在"
    vdbImportConflictDesc = "代码为「%s」的自定义数据库已存在。请输入其他代码，或保留「%s」以覆盖。"
    vdbImportConflictAction = "使用此代码导入"
    vdbOverwriteTitle = "覆盖数据库？"
    vdbOverwriteDesc = "代码为「%s」的自定义数据库已存在。保存将永久替换其中的经文，且无法撤销。"
    vdbOverwriteConfirm = "覆盖"

    // --- 将经文分享为图片 ---
    share = "分享"
    shareDialogTitle = "分享经文"
    shareDialogDesc = "选择操作"
    shareAction = "分享"
    shareActionDesc = "通过其他应用发送图片"
    saveToGalleryAction = "保存到相册"
    saveToGalleryActionDesc = "将图片保存到本设备"
    shareSuccess = "经文已分享"
    shareFailed = "分享经文失败"
    saveSuccess = "经文已保存到相册"
    saveFailed = "保存到相册失败"
    shareImageDesc = "用于分享的经文图片"

    // --- 收藏经文 ---
    favorites = "收藏"
    favoritesTitle = "收藏的经文"
    favoritesEmpty = "你还没有收藏任何经文"
    favoritesEmptyDesc = "在预览中点按星标即可添加经文。"
    addToFavorites = "添加到收藏"
    removeFromFavorites = "从收藏中移除"
    favoritesCount = "%d 项收藏"
    setAsWallpaper = "设为壁纸"
    confirmRemoveFavoriteTitle = "从收藏中移除？"
    confirmRemoveFavoriteDesc = "该经文将从你的收藏中移除。"
    addedToFavorites = "经文已添加到收藏"
    removedFromFavorites = "经文已从收藏中移除"
    addedOn = "添加于 %s"

    // --- 收藏卡片样式 / 多选 ---
    favoritesSubtitle = "点按一节经文即可设为壁纸"
    favSelectMode = "选择"
    favDeleteSelected = "移除所选"
    favSelected = "已选择"
    favSelectAll = "全选"
    favDeselectAll = "取消全选"
    favDeleteConfirm = "移除所选经文？"
    favDeleteConfirmDesc = "这些经文将从你的收藏中移除。"
    favRemovedCount = "已移除 %d 节经文"
    favCardStyleLabel = "收藏卡片样式"
    favCardStyleQuote = "详细"
    favCardStyleQuoteDesc = "带操作栏的经文"
    favCardStyleCompact = "紧凑"
    favCardStyleCompactDesc = "紧凑的列表行"
    favCardStyleHero = "大字引用"
    favCardStyleHeroDesc = "大幅海报式引用"
}

// -----------------------------------------------------------------------------
// 语言名称的本地化（简体中文）
// 供 设置 → 应用语言 / 经文语言 选择器显示为「本地名称 (中文名称)」。
// 需在 AppStrings.kt 的 localizedLangNamesFor() 中注册：
//     "ZH" -> zhLocalizedLangNames
// -----------------------------------------------------------------------------

val zhLocalizedLangNames: Map<String, String> = mapOf(
    "EN" to "英语",
    "SK" to "斯洛伐克语",
    "CZ" to "捷克语",
    "ES" to "西班牙语",
    "IT" to "意大利语",
    "FR" to "法语",
    "DE" to "德语",
    "HU" to "匈牙利语",
    "PL" to "波兰语",
    "ZH" to "简体中文"
)
